node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
     env.docker_cmd = "${tool('docker-default')}/bin/docker"
     sh "echo ${docker_cmd} -v"
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs-latest') {
       sh 'cd web/'
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     withDockerRegistry([url: 'https://index.docker.io/v1/', credentialsId: 'dockerhub']) {
        sh "${docker_cmd} build -t='chernikovp/docker-jenkins-demo:${commit_id}' web/"
        sh "${docker_cmd} push chernikovp/docker-jenkins-demo:${commit_id}"
     }
   }
}
