node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
     env.docker_cmd = "${tool('docker-latest')}/bin/docker"
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs-latest') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     withDockerRegistry(url: 'https://index.docker.io/v1/', credentialsId: 'dockerhub') {
        sh "${docker_cmd} build -t='https://index.docker.io/v1/docker-jenkins-demo:${commit_id}' ."
        sh "${docker_cmd} push https://index.docker.io/v1/docker-jenkins-demo:${commit_id}"
     }
   }
}
